/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import java.awt.FlowLayout;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Antho
 */
public class AgregarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCuenta
     */
    public AgregarCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSopas = new javax.swing.JButton();
        jButtonArroces = new javax.swing.JButton();
        jButtonEnsaladas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonGaseosas = new javax.swing.JButton();
        jButtonAguas = new javax.swing.JButton();
        jButtonAlcoholicas = new javax.swing.JButton();
        jButtonJugosNaturales = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreDelCliente = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Cliente:");

        jLabel3.setText("Platos");

        jButtonSopas.setText("Sopas");
        jButtonSopas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSopasActionPerformed(evt);
            }
        });

        jButtonArroces.setText("Arroces");
        jButtonArroces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArrocesActionPerformed(evt);
            }
        });

        jButtonEnsaladas.setText("Ensaladas");
        jButtonEnsaladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnsaladasActionPerformed(evt);
            }
        });

        jLabel4.setText("Bebidas");

        jButtonGaseosas.setText("Gaseosas");
        jButtonGaseosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGaseosasActionPerformed(evt);
            }
        });

        jButtonAguas.setText("Aguas");
        jButtonAguas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAguasActionPerformed(evt);
            }
        });

        jButtonAlcoholicas.setText("Alcoholicas");
        jButtonAlcoholicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlcoholicasActionPerformed(evt);
            }
        });

        jButtonJugosNaturales.setText("Jugos naturales");
        jButtonJugosNaturales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugosNaturalesActionPerformed(evt);
            }
        });

        jLabel5.setText("Combos");

        jTextFieldNombreDelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreDelClienteActionPerformed(evt);
            }
        });

        jButton6.setText("Combo 1");

        jButton7.setText("Combo 2");

        jButton8.setText("Combo 3");

        jButton9.setText("AGREGAR");

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonSopas)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jButtonEnsaladas))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreDelCliente))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAlcoholicas))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonArroces)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(142, 142, 142))
                        .addComponent(jButtonAguas))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGaseosas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(92, 92, 92)
                                            .addComponent(jButtonJugosNaturales))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jButton6)
                                            .addGap(31, 31, 31)
                                            .addComponent(jButton7)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton8))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSopas)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNombreDelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonArroces)
                            .addComponent(jButtonEnsaladas))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGaseosas)
                            .addComponent(jButtonAguas)
                            .addComponent(jButtonAlcoholicas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonJugosNaturales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonArrocesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArrocesActionPerformed
        PlatosCategorias pc = new PlatosCategorias("arroces");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonArrocesActionPerformed

    private void jButtonSopasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSopasActionPerformed
        PlatosCategorias pc = new PlatosCategorias("sopas");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonSopasActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Mesas mesas = new Mesas();
        mesas.setVisible(true);
        this.setVisible(false);
        try {
            db.borrarCuentaKey();
        } catch (SQLException ex) {
            Logger.getLogger(AgregarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEnsaladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnsaladasActionPerformed
        PlatosCategorias pc = new PlatosCategorias("ensaladas");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonEnsaladasActionPerformed

    private void jButtonGaseosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGaseosasActionPerformed
        PlatosCategorias pc = new PlatosCategorias("gaseosas");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonGaseosasActionPerformed

    private void jButtonAguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAguasActionPerformed
        PlatosCategorias pc = new PlatosCategorias("aguas");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonAguasActionPerformed

    private void jButtonAlcoholicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlcoholicasActionPerformed
        PlatosCategorias pc = new PlatosCategorias("alcohol");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonAlcoholicasActionPerformed

    private void jButtonJugosNaturalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugosNaturalesActionPerformed
        PlatosCategorias pc = new PlatosCategorias("jugos naturales");
        pc.setVisible(true);
        actualizarNombre();
    }//GEN-LAST:event_jButtonJugosNaturalesActionPerformed

    private void jTextFieldNombreDelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreDelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreDelClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCuenta().setVisible(true);
            }
        });
    }

    public void actualizarNombre() {
        try {
            db.asignarNombreCliente(jTextFieldNombreDelCliente.getText());
        } catch (SQLException ex) {
            Logger.getLogger(AgregarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    MySQL db = new MySQL();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAguas;
    private javax.swing.JButton jButtonAlcoholicas;
    private javax.swing.JButton jButtonArroces;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnsaladas;
    private javax.swing.JButton jButtonGaseosas;
    private javax.swing.JButton jButtonJugosNaturales;
    private javax.swing.JButton jButtonSopas;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldNombreDelCliente;
    // End of variables declaration//GEN-END:variables

}
